### ISSUE TITLE
Input from Nix on native dependencies specification & pkg-config usage

### ISSUE THREAD

**Issue by rgommers** [rgommers/peps#8]
@domenkozar to follow-up on https://discuss.python.org/t/pkgconfig-specification-as-an-alternative-to-ctypes-util-find-library/31379: could you have a look at https://github.com/rgommers/peps/blob/pep-external-deps/pep-9999.rst and see if the metadata for native dependencies and the `pkg-config` example cover what you need here in terms of metadata? 

I'll note that it does not cover installing `.pc` files and putting them on the `pkg-config` search path, that will need a separate topic/PEP. The majority of shared/static library usage in Python packages is for libraries that don't come from PyPI though, and for those I think the current PEP is already enough.

**Comment by domenkozar** [comment]
In the Nix land, we take care of installing `.pc` files, so that's not an issue.

This looks good, one question I had is how does pkg-config integrate into this? Any dependency as declared is looked up using `pkg-config` by it's name?

**Comment by rgommers** [comment]
Great, thanks for checking it out.

> This looks good, one question I had is how does pkg-config integrate into this? Any dependency as declared is looked up using `pkg-config` by it's name?

That is a per-package question rather than having to do with Python packaging standardization. Each Python package has to choose a build system and build backend (those may be the same, or not), and then they have to use that to do dependency discovery. I'd say the current state of things is:

- `meson`/`meson-python`: the preferred mechanims is using `pkg-config`, and Meson is able to use CMake's dependency detection as a fallback method. There's also `configtool` support, which is at least used for `pybind11`, and custom dependency providers that may be implemented for widely used libraries like Boost.
- `cmake` / `scikit-build-core`: the preferred mechanism is `.cmake` files, and it can also use `pkg-config` and `configtool`.
- `setuptools`: mostly ad-hoc things implemented in Python code directly.
- pure-Python-only build backends: these deal only with pure Python packages and don't know anything about compilers; there may still be packages around that use `ctypes` et al. to directly interact with shared libraries. Not common though as far as I know.

All we can really do here is provide docs and point at packages that do things in a way we'd consider best-practice.

**Comment by rgommers** [comment]
Looks like we're good here, so I'll close this issue. Thanks Domen!
